spring:
  application:
    name: app

  datasource:
    url: jdbc:postgresql://localhost:5432/propostadb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Mude para 'create' se precisar criar as tabelas do zero
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
